// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WhatsAppClone.Models;

public partial class Chat
{
    public Guid Id { get; set; }

    public bool? IsGroup { get; set; }

    public string GroupName { get; set; }

    public string GroupImage { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<ChatParticipant> ChatParticipants { get; set; } = new List<ChatParticipant>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}