// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WhatsAppClone.Models;

public partial class GroupMessage
{
    public Guid Id { get; set; }

    public Guid GroupId { get; set; }

    public Guid? SenderId { get; set; }

    public string Content { get; set; }

    public string MessageType { get; set; }

    public string MediaUrl { get; set; }

    public DateTime? Timestamp { get; set; }

    public virtual Group Group { get; set; }

    public virtual ICollection<GroupMessageStatus> GroupMessageStatuses { get; set; } = new List<GroupMessageStatus>();

    public virtual User Sender { get; set; }
}