// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WhatsAppClone.Models;

public partial class Message
{
    public Guid Id { get; set; }

    public Guid ChatId { get; set; }

    public Guid SenderId { get; set; }

    public string Content { get; set; }

    public string MessageType { get; set; }

    public string MediaUrl { get; set; }

    public DateTime? Timestamp { get; set; }

    public virtual Chat Chat { get; set; }

    public virtual ICollection<MessageStatus> MessageStatuses { get; set; } = new List<MessageStatus>();

    public virtual User Sender { get; set; }
}