// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WhatsAppClone.Models;

public partial class MessageStatus
{
    public Guid Id { get; set; }

    public Guid MessageId { get; set; }

    public Guid ReceiverId { get; set; }

    public string Status { get; set; }

    public DateTime? Timestamp { get; set; }

    public virtual Message Message { get; set; }

    public virtual User Receiver { get; set; }
}