// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WhatsAppClone.Models;

public partial class Notification
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public string Title { get; set; }

    public string Message { get; set; }

    public DateTime? Timestamp { get; set; }

    public bool? IsRead { get; set; }

    public virtual User User { get; set; }
}