// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WhatsAppClone.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string PhoneNumber { get; set; }

    public string Tcno { get; set; }

    public string SicilNo { get; set; }

    public string Name { get; set; }

    public string SurName { get; set; }

    public string ProfileImage { get; set; }

    public string Status { get; set; }

    public DateTime? LastSeen { get; set; }

    public bool? IsOnline { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpires { get; set; }

    public bool isAddToGroup { get; set; }

    public virtual ICollection<ChatParticipant> ChatParticipants { get; set; } = new List<ChatParticipant>();

    public virtual ICollection<GroupInvite> GroupInviteInvitees { get; set; } = new List<GroupInvite>();

    public virtual ICollection<GroupInvite> GroupInviteInviters { get; set; } = new List<GroupInvite>();

    public virtual ICollection<GroupMember> GroupMembers { get; set; } = new List<GroupMember>();

    public virtual ICollection<GroupMessageStatus> GroupMessageStatuses { get; set; } = new List<GroupMessageStatus>();

    public virtual ICollection<GroupMessage> GroupMessages { get; set; } = new List<GroupMessage>();

    public virtual ICollection<Group> Groups { get; set; } = new List<Group>();

    public virtual ICollection<MessageStatus> MessageStatuses { get; set; } = new List<MessageStatus>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();
}